# Generated by Django 5.0.6 on 2024-09-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('stock_quantity', models.IntegerField(default=0)),
                ('categories', models.ManyToManyField(to='category.category')),
            ],
        ),
    ]
