# Generated by Django 5.0.6 on 2024-10-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_saleitem_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='products',
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
