# Generated by Django 5.0.6 on 2024-10-08 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_saleitem_products_alter_saleitem_quantity'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
