# Generated by Django 5.0.6 on 2024-10-08 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_saleitem_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='products',
            new_name='product',
        ),
    ]
